// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuUE37tqjKzM0ug6B-5ABOC-Gnvm3zRtA',
    appId: '1:939758560117:web:dfbcb3cb94e5216e24e93c',
    messagingSenderId: '939758560117',
    projectId: 'todo-project-0001-2012d',
    authDomain: 'todo-project-0001-2012d.firebaseapp.com',
    storageBucket: 'todo-project-0001-2012d.firebasestorage.app',
    measurementId: 'G-W92WKRHDEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxjJTM0UVlUGVLH-MlkhrvKK7eOBQjCh4',
    appId: '1:939758560117:android:5785e1bd66e2608d24e93c',
    messagingSenderId: '939758560117',
    projectId: 'todo-project-0001-2012d',
    storageBucket: 'todo-project-0001-2012d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnLUU6i33HuN-Ss9BofqmBGwqqN6FC8Ik',
    appId: '1:939758560117:ios:97fefd284084d42724e93c',
    messagingSenderId: '939758560117',
    projectId: 'todo-project-0001-2012d',
    storageBucket: 'todo-project-0001-2012d.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnLUU6i33HuN-Ss9BofqmBGwqqN6FC8Ik',
    appId: '1:939758560117:ios:97fefd284084d42724e93c',
    messagingSenderId: '939758560117',
    projectId: 'todo-project-0001-2012d',
    storageBucket: 'todo-project-0001-2012d.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuUE37tqjKzM0ug6B-5ABOC-Gnvm3zRtA',
    appId: '1:939758560117:web:d31a6d3828e9da8424e93c',
    messagingSenderId: '939758560117',
    projectId: 'todo-project-0001-2012d',
    authDomain: 'todo-project-0001-2012d.firebaseapp.com',
    storageBucket: 'todo-project-0001-2012d.firebasestorage.app',
    measurementId: 'G-TE3CPYYZKG',
  );
}
